;; This file will contain Bufs mode.

(defun bufs-make-mode-map ()
  "Creates and returns a mode map with bufs's key bindings."
  (let ((keymap (make-sparse-keymap)))
    (define-key keymap "?" 'nav-help-screen)
    (define-key keymap "`" 'nav)
    (define-key keymap [S-down-mouse-3] 'nav-start-bufs-mode)
    (define-key keymap [(control ?x) (control ?f)] 'find-file-other-window)
    keymap))

(setq bufs-mode-map (bufs-make-mode-map))

(defun bufs-show-buffers ()
  (interactive)
  (let ((inhibit-read-only t))
    (erase-buffer)
    (setq blist (mapcar (function buffer-name) (buffer-list)))
    (insert (nav-make-buffers-header "Active Buffers:     " ))
    (insert "\n")
    (dolist (b blist)
      (when (not (string-match "^[ *]" b))
            (insert-text-button b :type 'buffer-jump-button)
            (insert "\n")))
    (insert "\n")
    (insert (nav-make-buffers-header "Scratch Buffers:    "))
    (insert "\n")
    (dolist (b blist)
      (when (string-match "^\\*" b)
        (insert-text-button b :type 'buffer-jump-button)
        (insert "\n")))
    (setq mode-line-format "nav: Buffer list")
    (force-mode-line-update))
  (goto-line 2))
